name: kiddytunes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  custom_sliding_segmented_control: ^1.8.1
  lottie: ^2.7.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kt_logo.png
    - assets/images/dancer.png
    - assets/images/headphones.png
    - assets/images/love.png
    - assets/images/Avatar1.svg
    - assets/images/Avatar2.svg
    - assets/images/Avatar3.svg
    - assets/images/Avatar4.svg
    - assets/images/next.svg
    - assets/images/music_icon.svg
    - assets/images/stylish_search.svg
    - assets/images/heart_icon.png
    - assets/images/music_logo.png
    - assets/images/final_music_svg.svg
    - assets/images/Heart_svg.svg
    - assets/images/love_song.svg
    - assets/images/play_fab.svg
    - assets/images/spiral_bind.svg
    - assets/images/white_fab.svg
    - assets/animations/heart_animation.json
    - assets/animations/Ghost_notfound.json
    - assets/animations/orange_search.json
    - assets/Baa_black sheep.mp3
    - assets/baby-shark.mp3
    - assets/Bingo-Song-Singing-Bell.mp3
    - assets/Deck-the-halls-Singing-Bell.mp3
    - assets/Five-little-monkeys-Singing-Bell.mp3
    - assets/For he jolly.mp3
    - assets/Head-Shoulders-Knees-and-Toes.mp3
    - assets/Humpty-Dumpty.mp3
    - assets/Hush-Little-Baby-Singing-Bell.mp3
    - assets/I-m-a-little-teapot-Singing-Bell.mp3
    - assets/Itsy-Bitsy-Spider-Singing-Bell.mp3
    - assets/Jack and jill.mp3
    - assets/Jingle-Bells-Singing-Bell.mp3
    - assets/Joy to the world_afrobeat.mp3
    - assets/London bridge.mp3
    - assets/Mary had a little lamb.mp3
    - assets/old-macdonald-had-a-farm.mp3
    - assets/Pop-Goes-the-weasel-Singing-Bell.mp3
    - assets/Rain Rain go away.mp3
    - assets/Row your boat.mp3
    - assets/she'll be coming round the mountain.mp3
    - assets/silent_Night.mp3
    - assets/Ten-in-the-Bed-Singing-Bell.mp3
    - assets/The-more-we-get-together-Singing-Bell.mp3
    - assets/this_old_man.mp3
    - assets/Twinkle_little_star.mp3
    - assets/wheels on the bus.mp3
    - assets/alphabet song.mp3
    - assets/if you're happy and you know it.mp3
    - assets/Baby-Bumblebee-Singing-Bell.mp3
    - assets/Rock-a-bye-baby.mp3
    

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
